spring.application.name: ProcessService
server:
  port: 8182
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: "consumer-1"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: ru.mts.homework.serializer.ApplicationDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
    producer:
      auto-offset-reset: earliest
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: ru.mts.homework.serializer.AppStatusSerializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
    application:
      delete-upon-undeploy: false
      scan-for-process-definitions: true
      deploy-changed-only: true
      resume-previous-versions: true
      resume-previous-by: a value
    job-execution:
      enabled: true
    metrics:
      enabled: false
      db-reporter-activate: false


camunda.bpm.auto-deployment-enabled: false